<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */

declare(strict_types=1);

return [
  'dependencies' => [
    'factories' => [
      Access\Handler\AccessHandler::class => Access\Handler\AccessHandlerFactory::class,
      Company\Handler\CompanyCreateHandler::class => Company\Handler\CompanyCreateHandlerFactory::class,
      Company\Handler\CompanyReadHandler::class => Company\Handler\CompanyReadHandlerFactory::class,
      Company\Handler\CompanyReadAllHandler::class => Company\Handler\CompanyReadAllHandlerFactory::class,
      Company\Handler\CompanyUpdateHandler::class => Company\Handler\CompanyUpdateHandlerFactory::class,
    ],
  ],
];
