<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Access\Handler\AccessHandler::class => Access\Handler\AccessHandlerFactory::class,
            Company\Handler\CompanyHandlerCreate::class => Company\Handler\CompanyHandlerFactoryCreate::class,
            Company\Handler\CompanyHandlerRead::class => Company\Handler\CompanyHandlerFactoryRead::class,
            Company\Handler\CompanyHandlerReadAll::class => Company\Handler\CompanyHandlerReadAllFactory::class,
            Company\Handler\CompanyHandlerUpdate::class => Company\Handler\CompanyHandlerUpdateFactory::class,
        ],
    ],
];
